# This is a basic workflow to help you get started with Actions

name: test push dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: set time
        run: timedatectl set-timezone 'Asia/Shanghai'
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          

      - name: Restore cached Primes
        uses: actions/checkout@v3
        with: 
          ref:  dev
          path: 'dev'
          
      - name: Run script
        run: |
          ls
          cd dev
          git log -n2
          echo "♻ $(date '+%Y-%m-%d %H:%M:%S')\n" >> dev
          
          git config user.email "github-+bot@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "asa-$(date '+%Y-%m-%d %H:%M:%S')"
          
          git push https://oauth2:${{secrets.PERSONAL_TOKEN}}@github.com/ts-sf/test-abc.git dev
