# This is a basic workflow to help you get started with Actions

name: test push dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          

          
      - name: Run script
        run: |
          git config user.email "github-+bot@github.com"
          git config user.name "actions"
          echo "♻ $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")\n" >> main
          git add main
          git commit -m "main-$(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          git push
          git checkout dev

          git log -n2
          echo "♻ $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")\n" >> dev
          git add dev
          git commit -m "asa-$(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          
          git push
